Repository bitshares/bitshares-core, pull requests merged in 2018-06, with the labels that each got.

#1015 Fix wallet in-code docs
  libraries/wallet/include/graphene/wallet/wallet.hpp
Labels: 1c Task, 2e Ready for Testing, 3c Enhancement

#1041 Skip temp-account balance check
  libraries/chain/db_block.cpp
  libraries/chain/hardfork.d/CORE_1040.hf
  tests/tests/block_tests.cpp
Labels: hardfork

#1038 Issue1013, New API: get transaction hex without `signatures` field
  libraries/app/database_api.cpp
  libraries/app/include/graphene/app/database_api.hpp
  tests/tests/database_api_tests.cpp
Labels: 1c Task, 2g Final Review, 3c Enhancement

#1039 Issue1011, Add CLI startup option to only generate keys
  libraries/wallet/include/graphene/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  programs/cli_wallet/main.cpp
Labels: 1c Task, 2g Final Review, 3c Enhancement, 5a Docs Needed, 6 CLI

#1019 Add index on short_backing_asset (Issue 960)
  libraries/chain/asset_evaluator.cpp
  libraries/chain/include/graphene/chain/asset_object.hpp
  tests/common/database_fixture.hpp
  tests/tests/bitasset_tests.cpp
Labels: 1c Task, 2g Final Review, 3c Enhancement
