Repository bitshares/bitshares-core, pull requests merged in 2018-04, with the labels that each got.

#827 bsip30 part 2: disallow increasing debt when updating short position
  libraries/chain/market_evaluator.cpp
  tests/tests/operation_tests.cpp
Labels: hardfork

#804 Move node and application implementations to header file
  libraries/app/application.cpp
  libraries/app/application_impl.hxx
  libraries/net/node.cpp
  libraries/net/node_impl.hxx
  tests/CMakeLists.txt
  tests/app/main.cpp
  tests/cli/main.cpp
  tests/common/genesis_file_util.hpp
Labels: code cleanup, testing

#829 BSIP31-34 market engine improvements
  libraries/chain/db_maint.cpp
  libraries/chain/db_market.cpp
  libraries/chain/db_update.cpp
  libraries/chain/hardfork.d/CORE_338.hf
  libraries/chain/hardfork.d/CORE_343.hf
  libraries/chain/hardfork.d/CORE_453.hf
  libraries/chain/hardfork.d/CORE_606.hf
  libraries/chain/hardfork.d/CORE_625.hf
  libraries/chain/include/graphene/chain/database.hpp
  libraries/chain/include/graphene/chain/market_object.hpp
  libraries/chain/market_evaluator.cpp
  tests/tests/market_tests.cpp
Labels: hardfork

#857 Revised HF protection for #214 with additional test scenario
  libraries/chain/proposal_evaluator.cpp
  tests/tests/authority_tests.cpp
Labels: hardfork

#813 fix memory access violation
  libraries/app/api.cpp
Labels: 2a Discussion Needed

#830 BSIP35 mitigate rounding issue when matching orders
  libraries/chain/asset_evaluator.cpp
  libraries/chain/db_market.cpp
  libraries/chain/db_update.cpp
  libraries/chain/hardfork.d/CORE_184.hf
  libraries/chain/hardfork.d/CORE_342.hf
  libraries/chain/include/graphene/chain/asset_object.hpp
  libraries/chain/include/graphene/chain/protocol/asset.hpp
  libraries/chain/protocol/asset.cpp
  tests/common/database_fixture.hpp
  tests/tests/basic_tests.cpp
  tests/tests/fee_tests.cpp
  tests/tests/market_rounding_tests.cpp
  tests/tests/market_tests.cpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_tests2.cpp
  tests/tests/settle_tests.cpp
Labels: hardfork

#883 More test cases for bsip35
  libraries/chain/proposal_evaluator.cpp
  tests/tests/settle_tests.cpp
Labels: hardfork
