Repository bitshares/bitshares-core, pull requests merged in 2018-10, with the labels that each got.

#1351 add asset names and amount/price calculations to additional
  libraries/plugins/elasticsearch/elasticsearch_plugin.cpp
  libraries/plugins/elasticsearch/include/graphene/elasticsearch/elasticsearch_plugin.hpp
Labels: 6 Plugin, 6 UX

#1359 Performance opt pt 1
  libraries/chain/account_object.cpp
  libraries/chain/db_block.cpp
  libraries/chain/db_management.cpp
  libraries/chain/include/graphene/chain/account_object.hpp
Labels: 2f Testing, 3c Enhancement, 6 Performance

#1323 wallet compatibility issue
  libraries/wallet/wallet.cpp
Labels: 2g Final Review
