Repository bitshares/bitshares-core, pull requests merged in 2019-03, with the labels that each got.

#1587 support for Boost 1.69
  README.md
Labels: documentation

#1032 Issue867 Add CLI command to add signatures to a partially signed transaction
  libraries/wallet/include/graphene/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  tests/cli/main.cpp
Labels: 1b User Story, 2d Developing, 3b Feature, 5a Docs Needed, 6 CLI

#1662 Improve fee_schedule::calculate_fee() performance
  libraries/chain/include/graphene/chain/protocol/fee_schedule.hpp
  libraries/chain/protocol/fee_schedule.cpp
Labels: performance
